# Generated by Django 5.0.2 on 2024-02-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('bg_color', models.CharField(choices=[('blue', 'Blue'), ('orange', 'Orange'), ('purple', 'Purple'), ('green', 'Green'), ('black', 'Black')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylinks', to='linktree.profile')),
            ],
        ),
    ]
